/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homologaciones;

import com.sun.awt.AWTUtilities;
import static homologaciones.Registro_equivalencia_otra_universidad.JTAsignaturas;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Cristian
 */
public class Agregar_Asignatura extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_Asignatura
     */
    int x;
    int y;
    int control=0;
    int datousuario=0;
   
  
    public Agregar_Asignatura() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
    }

     public void setControl(int controlP, int dato) {
        control=controlP;
        datousuario= dato;
         System.out.println("eeeeeoooooo"+datousuario);
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cod_Asig = new javax.swing.JTextField();
        Nom_Asig = new javax.swing.JTextField();
        Nota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Agregar = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLTexto_superior = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jBCancelar = new javax.swing.JButton();
        jBConfirmar = new javax.swing.JButton();
        jBAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cod_Asig.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        getContentPane().add(Cod_Asig, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 260, 30));

        Nom_Asig.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        Nom_Asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_AsigActionPerformed(evt);
            }
        });
        getContentPane().add(Nom_Asig, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 260, 30));

        Nota.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        Nota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NotaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NotaKeyTyped(evt);
            }
        });
        getContentPane().add(Nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 150, 30));

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel1.setText("Codigo Asignatura");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel2.setText("Nota");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel3.setText("Nombre Asignatra");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        Tabla_Agregar.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        Tabla_Agregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Asignatura", "Nombre Asignatura", "Nota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_Agregar);
        if (Tabla_Agregar.getColumnModel().getColumnCount() > 0) {
            Tabla_Agregar.getColumnModel().getColumn(0).setResizable(false);
            Tabla_Agregar.getColumnModel().getColumn(1).setResizable(false);
            Tabla_Agregar.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 730, 210));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoUnivalle.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLTexto_superior.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLTexto_superior.setForeground(new java.awt.Color(255, 0, 0));
        jLTexto_superior.setText("UNIVERSIDAD DEL VALLE");
        jLTexto_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLTexto_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLTexto_superiorMouseDragged(evt);
            }
        });
        jLTexto_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLTexto_superiorMousePressed(evt);
            }
        });
        getContentPane().add(jLTexto_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jLCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 920, 20));

        jBCancelar.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jBCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setBorder(null);
        jBCancelar.setBorderPainted(false);
        jBCancelar.setContentAreaFilled(false);
        jBCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 110, 40));

        jBConfirmar.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jBConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jBConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jBConfirmar.setText("Enlistar asignaturas");
        jBConfirmar.setBorder(null);
        jBConfirmar.setBorderPainted(false);
        jBConfirmar.setContentAreaFilled(false);
        jBConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 190, 40));

        jBAgregar.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jBAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jBAgregar.setText("Agregar asignatura");
        jBAgregar.setBorder(null);
        jBAgregar.setBorderPainted(false);
        jBAgregar.setContentAreaFilled(false);
        jBAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 190, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recuadro_base.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nom_AsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_AsigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_AsigActionPerformed

  
            
    private void NotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NotaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaKeyPressed

    private void NotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NotaKeyTyped
         double n = evt.getKeyChar(); // KeyChar Obtiene o establece el carácter correspondiente a la tecla presionada.
       
       if((n<'0' || n>'5')&& (n<',' || n>'.')){
           evt.consume();
       }
    }//GEN-LAST:event_NotaKeyTyped

    private void jLTexto_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTexto_superiorMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLTexto_superiorMouseDragged

    private void jLTexto_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTexto_superiorMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jLTexto_superiorMousePressed

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null,"¿Desea salir del programa?");
        if(opcion ==JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
       Registro_equivalencia_otra_universidad a= new Registro_equivalencia_otra_universidad();  
       a.setControl(control,datousuario );
        int opciones = JOptionPane.showConfirmDialog(null,"¿Desea agregar la asignatura?");
           if(opciones==JOptionPane.YES_OPTION){
        
          String Codigo_Asignatura = Cod_Asig.getText();
          String Nombre_Asignatura = Nom_Asig.getText();
          double nota =Double.valueOf(Nota.getText());
          
         DefaultTableModel modelo1 = (DefaultTableModel) Tabla_Agregar.getModel();


        
        Object [] fila = new Object[3];

        fila[0]=Codigo_Asignatura;
        fila[1]=Nombre_Asignatura;
        fila[2]=nota;
      
        modelo1.addRow(fila);
        Cod_Asig.setText("");
        Nom_Asig.setText("");
        Nota.setText("");
        Tabla_Agregar.setModel(modelo1);

    }
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        // TODO add your handling code here:
         Registro_equivalencia_otra_universidad b = new Registro_equivalencia_otra_universidad();
        b.setControl(control,datousuario);
        TableModel modelo1= Tabla_Agregar.getModel();
        
        Registro_equivalencia_otra_universidad.JTAsignaturas.setModel(modelo1);
           
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        Registro_equivalencia_otra_universidad volver = new Registro_equivalencia_otra_universidad();
       volver.setControl(control,datousuario);
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Agregar_Asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Agregar_Asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Agregar_Asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Agregar_Asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                 try {
//                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); //hace parte de lo del marco de la interfaz
//                    
//                } catch (Exception ex) {
//                    System.out.println("Error de recuadro interfaz");
//                } 
//                new Agregar_Asignatura().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Cod_Asig;
    public static javax.swing.JTextField Nom_Asig;
    public static javax.swing.JTextField Nota;
    public static javax.swing.JTable Tabla_Agregar;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLTexto_superior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
