/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homologaciones;

import com.sun.awt.AWTUtilities;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOHN EDWAR
 */
public class Consultar_solicitudes_equivalencia extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_solicitudes_equivalencia
     */
    int x,y;
    conexionBD conexion = new conexionBD();
    int control; // control es el valor que define si ingreso un gestor o un estudiante
    int datoUsuario; // aqui se guarda el codigo del estudiante que inicio sesion, codigo de origen
    
    public Consultar_solicitudes_equivalencia() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false); 
        
        jBVer.setEnabled(false);
        jBAREchazarSolicitud.setEnabled(false);
        jBAprobarSolicitud.setEnabled(false);
    }
    public void setControl(int controlP,int dato) {
        datoUsuario=dato;
        control=controlP;
        
        if(control==1){

            jLDesde.setVisible(false);
            jLHasta.setVisible(false);
            rSDateDesde.setVisible(false);
            rSDateHasta.setVisible(false);
            jBRealizarBusqueda.setVisible(false);
            jBAREchazarSolicitud.setVisible(false);
            jBAprobarSolicitud.setVisible(false);
            
            String sql="select * from solicitud where codFicha='"+datoUsuario+"'";
            conexion.consulta(sql);
            
            ArrayList<String[]> datos = conexion.consulta(sql);
            
            DefaultTableModel modelo = (DefaultTableModel)jTSolicitudes.getModel();
     
            while(modelo.getRowCount() > 0){
                modelo.removeRow(0);
            }
            for(String[] fila : datos){           
                modelo.addRow(fila);

           }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLTexto_superior = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jLHasta = new javax.swing.JLabel();
        jLDesde = new javax.swing.JLabel();
        jBAREchazarSolicitud = new javax.swing.JButton();
        jBAprobarSolicitud = new javax.swing.JButton();
        jBVer = new javax.swing.JButton();
        jBRealizarBusqueda = new javax.swing.JButton();
        jScrollSolicitudes = new javax.swing.JScrollPane();
        jTSolicitudes = new javax.swing.JTable();
        rSDateDesde = new rojeru_san.componentes.RSDateChooser();
        rSDateHasta = new rojeru_san.componentes.RSDateChooser();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono cerrar sesion.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, 60, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 40, 60));

        jButton1.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton1.setText("Programas");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 40, 60));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 40, 60));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 40, 60));

        jButton5.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton5.setText("Equivalencias");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jButton3.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton3.setText("Asignaturas");
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jButton6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 40, 60));

        jButton2.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton2.setText("Facultades");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLTexto_superior.setFont(new java.awt.Font("Open Sans", 0, 30)); // NOI18N
        jLTexto_superior.setForeground(new java.awt.Color(255, 0, 0));
        jLTexto_superior.setText("UNIVERSIDAD DEL VALLE");
        jLTexto_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLTexto_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLTexto_superiorMouseDragged(evt);
            }
        });
        jLTexto_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLTexto_superiorMousePressed(evt);
            }
        });
        getContentPane().add(jLTexto_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoUnivalle.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jLCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        jLHasta.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLHasta.setText("Hasta");
        getContentPane().add(jLHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        jLDesde.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLDesde.setText("Desde");
        getContentPane().add(jLDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jBAREchazarSolicitud.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jBAREchazarSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        jBAREchazarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jBAREchazarSolicitud.setText("Rechazar solicitud");
        jBAREchazarSolicitud.setBorder(null);
        jBAREchazarSolicitud.setBorderPainted(false);
        jBAREchazarSolicitud.setContentAreaFilled(false);
        jBAREchazarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAREchazarSolicitud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAREchazarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAREchazarSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(jBAREchazarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 640, 190, 40));

        jBAprobarSolicitud.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jBAprobarSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        jBAprobarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jBAprobarSolicitud.setText("Aprobar solicitud");
        jBAprobarSolicitud.setBorder(null);
        jBAprobarSolicitud.setBorderPainted(false);
        jBAprobarSolicitud.setContentAreaFilled(false);
        jBAprobarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAprobarSolicitud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAprobarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAprobarSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(jBAprobarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 190, 40));

        jBVer.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jBVer.setForeground(new java.awt.Color(255, 255, 255));
        jBVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jBVer.setText("Ver");
        jBVer.setBorder(null);
        jBVer.setBorderPainted(false);
        jBVer.setContentAreaFilled(false);
        jBVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBVer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerActionPerformed(evt);
            }
        });
        getContentPane().add(jBVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, 70, 30));

        jBRealizarBusqueda.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jBRealizarBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jBRealizarBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jBRealizarBusqueda.setText("Realizar busqueda");
        jBRealizarBusqueda.setBorder(null);
        jBRealizarBusqueda.setBorderPainted(false);
        jBRealizarBusqueda.setContentAreaFilled(false);
        jBRealizarBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBRealizarBusqueda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBRealizarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRealizarBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(jBRealizarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 190, 40));

        jTSolicitudes.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Solicitud", "Estado", "Codigo", "Nombre", "Fecha", "Destino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTSolicitudesMouseClicked(evt);
            }
        });
        jScrollSolicitudes.setViewportView(jTSolicitudes);

        getContentPane().add(jScrollSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 630, 240));

        rSDateDesde.setColorBackground(new java.awt.Color(207, 32, 62));
        rSDateDesde.setColorButtonHover(new java.awt.Color(207, 32, 62));
        rSDateDesde.setColorForeground(new java.awt.Color(0, 0, 0));
        rSDateDesde.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        rSDateDesde.setFuente(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        getContentPane().add(rSDateDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        rSDateHasta.setColorBackground(new java.awt.Color(207, 32, 62));
        rSDateHasta.setColorButtonHover(new java.awt.Color(207, 32, 62));
        rSDateHasta.setColorForeground(new java.awt.Color(0, 0, 0));
        rSDateHasta.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        rSDateHasta.setFuente(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        getContentPane().add(rSDateHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recuadro_base.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Equivalencias_interfaz equivalencia;
        equivalencia = new Equivalencias_interfaz();
        equivalencia.setControl(control,datoUsuario);
        this.dispose();
        equivalencia.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Asignaturas_interfaz asignaturas ;
        asignaturas = new Asignaturas_interfaz();
        asignaturas.setControl(control,datoUsuario);
        this.dispose();
        asignaturas.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLTexto_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTexto_superiorMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLTexto_superiorMouseDragged

    private void jLTexto_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTexto_superiorMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jLTexto_superiorMousePressed

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null,"¿Desea salir del programa?");
        if(opcion ==JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jBRealizarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRealizarBusquedaActionPerformed
        // TODO add your handling code here:
       if(rSDateDesde.getDatoFecha()!=null && rSDateHasta.getDatoFecha()!=null){
        String fomatoFecha ="dd-MM-yyyy";
        Date fechaDesde = rSDateDesde.getDatoFecha();
        Date fechaHasta = rSDateHasta.getDatoFecha();
        SimpleDateFormat formateador = new SimpleDateFormat(fomatoFecha);
        
        String sql="select * from solicitud where fecha between '"+formateador.format(fechaDesde)+"' and '"+formateador.format(fechaHasta)+"'";
        conexion.consulta(sql);
         
        ArrayList<String[]> datos = conexion.consulta(sql);
        
        DefaultTableModel modelo = (DefaultTableModel)jTSolicitudes.getModel();
     
            while(modelo.getRowCount() > 0){
                modelo.removeRow(0);
            }
            for(String[] fila : datos){           
                modelo.addRow(fila);

           }
         
        System.out.println("dasdasdasdasd: "+ rSDateDesde.getDatoFecha());
       }
       else{
           JOptionPane.showMessageDialog(null,"Porfavor digite los campos de fecha");
       }
       jBAREchazarSolicitud.setEnabled(false);
       jBAprobarSolicitud.setEnabled(false);
       jBVer.setEnabled(false);
    }//GEN-LAST:event_jBRealizarBusquedaActionPerformed

    private void jBVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerActionPerformed
        // TODO add your handling code here:
        Detalle_solicitud detalle = new Detalle_solicitud();
        
        try{
        int filaSel = jTSolicitudes.getSelectedRow();
        
        DefaultTableModel modelo = (DefaultTableModel)jTSolicitudes.getModel();
        String solicitud = (String) modelo.getValueAt(filaSel, 0);
        String estado = (String)modelo.getValueAt(filaSel,1);
        String codigo =  (String)modelo.getValueAt(filaSel,2);
        String nombre =  (String)modelo.getValueAt(filaSel,3);
        String programaDestino = (String)modelo.getValueAt(filaSel,5);
        
        detalle.setInformacion(estado, codigo, nombre, solicitud, programaDestino);
        if(control!=1){
//----------------------------------------------------------------------------------------------------------------
        String sql2="select estado from solicitud where numSolicitud='"+solicitud+"'";        
        ArrayList<String[]> datos = conexion.consulta(sql2);
        String estadoSol="";
        
        for(int i=0; i<datos.size(); i++){           
            
            String [] auxiliar =datos.get(i); // me trae el primer arreglo del arraylist en esta variable auxiliar
            estadoSol=auxiliar[i];
            System.out.println("Estado solicitud: "+ estadoSol);
            break;
        }
 //----------------------------------------------------------------------------------------
    if(estadoSol.equals("Pendiente")){
             System.out.println("Sid"+estado+" "+codigo+" "+nombre+" "+programaDestino);
        String sql="UPDATE solicitud SET estado= 'En revisión' WHERE numSolicitud='"+Integer.parseInt(solicitud)+"'";        
        conexion.sentencia(sql);
//----------------------------------------------------------------------------------------------------------       
         String fomatoFecha ="dd-MM-yyyy";
        Date fechaDesde = rSDateDesde.getDatoFecha();
        Date fechaHasta = rSDateHasta.getDatoFecha();
        SimpleDateFormat formateador = new SimpleDateFormat(fomatoFecha);
        
        String sql3="select * from solicitud where fecha between '"+formateador.format(fechaDesde)+"' and '"+formateador.format(fechaHasta)+"'";
        conexion.consulta(sql3);
         
        ArrayList<String[]> datos2 = conexion.consulta(sql3);
        
        modelo = (DefaultTableModel)jTSolicitudes.getModel();
     
            while(modelo.getRowCount() > 0){
                modelo.removeRow(0);
            }
            for(String[] fila : datos2){           
                modelo.addRow(fila);

           }
               }
        }
        }
        catch(Exception a1){
        JOptionPane.showMessageDialog(this,"\"Debe seleccionar una fila de la consulta primero \nantes de eliminar\"");
        }
        detalle.setVisible(true);
    }//GEN-LAST:event_jBVerActionPerformed

    private void jBAprobarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAprobarSolicitudActionPerformed
        // TODO add your handling code here:
        try{ 
        int opcion = JOptionPane.showConfirmDialog(null,"¿Esta seguro de aprobar la solicitud seleccionada?.Asegurese de haber revisado la solicitud ");
        if(opcion ==JOptionPane.YES_OPTION) {
            
            jBAREchazarSolicitud.setEnabled(false);
            jBAprobarSolicitud.setEnabled(false);
            jBVer.setEnabled(false);
        int filaSel = jTSolicitudes.getSelectedRow();
        
            DefaultTableModel modelo = (DefaultTableModel)jTSolicitudes.getModel();
            String solicitud = (String) modelo.getValueAt(filaSel, 0);
            String sql="UPDATE solicitud SET estado= 'Aprobada' WHERE numSolicitud='"+Integer.parseInt(solicitud)+"'";        
            conexion.sentencia(sql);
  //----------------------------------------------------------------------------------
            String fomatoFecha ="dd-MM-yyyy";
            Date fechaDesde = rSDateDesde.getDatoFecha();
            Date fechaHasta = rSDateHasta.getDatoFecha();
            SimpleDateFormat formateador = new SimpleDateFormat(fomatoFecha);

            String sql2="select * from solicitud where fecha between '"+formateador.format(fechaDesde)+"' and '"+formateador.format(fechaHasta)+"'";
            conexion.consulta(sql2);

            ArrayList<String[]> datos = conexion.consulta(sql2);

            modelo = (DefaultTableModel)jTSolicitudes.getModel();

                while(modelo.getRowCount() > 0){
                    modelo.removeRow(0);
                }
                for(String[] fila : datos){           
                    modelo.addRow(fila);

               }
            
               }
        }
        catch(Exception a1){
        JOptionPane.showMessageDialog(this,"\"Debe seleccionar una fila de la consulta primero \nantes de eliminar\"");
        }
        
       
    }//GEN-LAST:event_jBAprobarSolicitudActionPerformed

    private void jBAREchazarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAREchazarSolicitudActionPerformed
        // TODO add your handling code here:
         int opcion = JOptionPane.showConfirmDialog(null,"¿Esta seguro de Rechazar la solicitud seleccionada?.Asegurese de haber revisado la solicitud ");
        if(opcion ==JOptionPane.YES_OPTION) {
            
            jBAREchazarSolicitud.setEnabled(false);
            jBAprobarSolicitud.setEnabled(false);
            jBVer.setEnabled(false);
             try{
        int filaSel = jTSolicitudes.getSelectedRow();
        
            DefaultTableModel modelo = (DefaultTableModel)jTSolicitudes.getModel();
            String solicitud = (String) modelo.getValueAt(filaSel, 0);
            String sql="UPDATE solicitud SET estado= 'Rechazada' WHERE numSolicitud='"+Integer.parseInt(solicitud)+"'";        
            conexion.sentencia(sql);
       //----------------------------------------------------------------------------------------------
               String fomatoFecha ="dd-MM-yyyy";
            Date fechaDesde = rSDateDesde.getDatoFecha();
            Date fechaHasta = rSDateHasta.getDatoFecha();
            SimpleDateFormat formateador = new SimpleDateFormat(fomatoFecha);

            String sql2="select * from solicitud where fecha between '"+formateador.format(fechaDesde)+"' and '"+formateador.format(fechaHasta)+"'";
            conexion.consulta(sql2);

            ArrayList<String[]> datos = conexion.consulta(sql2);

            modelo = (DefaultTableModel)jTSolicitudes.getModel();

                while(modelo.getRowCount() > 0){
                    modelo.removeRow(0);
                }
                for(String[] fila : datos){           
                    modelo.addRow(fila);

               }
               }
        catch(Exception a1){
        JOptionPane.showMessageDialog(this,"\"Debe seleccionar una fila de la consulta primero \nantes de eliminar\"");
        }
        }
    }//GEN-LAST:event_jBAREchazarSolicitudActionPerformed

    private void jTSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTSolicitudesMouseClicked
        // TODO add your handling code here:
        jBVer.setEnabled(true);
         jBAREchazarSolicitud.setEnabled(true);
        jBAprobarSolicitud.setEnabled(true);
        
    }//GEN-LAST:event_jTSolicitudesMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null,"¿Desea cerrar sesion?");
        if(opcion ==JOptionPane.YES_OPTION) {
            try {
                Login_univalle log = new Login_univalle();
                this.dispose();
                log.setVisible(true);
            } catch (ClassNotFoundException ex) {
                
            }

        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Consultar_solicitudes_equivalencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Consultar_solicitudes_equivalencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Consultar_solicitudes_equivalencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Consultar_solicitudes_equivalencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                  try {
//                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); //hace parte de lo del marco de la interfaz
//                    
//                } catch (Exception ex) {
//                    System.out.println("Error de recuadro interfaz");
//                } 
//                new Consultar_solicitudes_equivalencia().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAREchazarSolicitud;
    private javax.swing.JButton jBAprobarSolicitud;
    private javax.swing.JButton jBRealizarBusqueda;
    private javax.swing.JButton jBVer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLDesde;
    private javax.swing.JLabel jLHasta;
    private javax.swing.JLabel jLTexto_superior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollSolicitudes;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTSolicitudes;
    private rojeru_san.componentes.RSDateChooser rSDateDesde;
    private rojeru_san.componentes.RSDateChooser rSDateHasta;
    // End of variables declaration//GEN-END:variables
}
