/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homologaciones;

import com.sun.awt.AWTUtilities;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOHN EDWAR
 */
public class Consultar_editar_asignaturas_interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_editar_asignaturas_interfaz
     */
    int x,y;
    conexionBD conexion = new conexionBD();
    int control;
    int datoUsuario=0;
    public void setControl(int variableControl,int dato){
        
       control=variableControl;
       datoUsuario=dato;
        System.out.println("Control en consultar ventana: "+control);
        if(control==1){
        jTNombreA.setVisible(false);
        jTCodigoA.setVisible(false);
        jTNumCreditos.setVisible(false);
        jLNombreA.setVisible(false);
        jLCodigoA.setVisible(false);
        jLNumCreditos.setVisible(false);
        jLHabilitable.setVisible(false);
        jLValidable.setVisible(false);
        jLEstado.setVisible(false);
        jRActivo.setVisible(false);
        jRInactivo.setVisible(false);
        jRNoHabilitable.setVisible(false);
        jRNoValidable.setVisible(false);
        jRSiHabilitable.setVisible(false);
        jRSiValidable.setVisible(false);
        jBEditar.setVisible(false);
        jSeparator1.setVisible(false);
        jSeparator5.setVisible(false);
        jTTipo.setVisible(false);
        jLTipo.setVisible(false);
        }
        
    }
    
    public Consultar_editar_asignaturas_interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        
       // para que cuando se abra la ventana ya aparezcan todos lo datos en la tablas
        String sql = "Select nombre,codAsignatura,tipo,numCreditos,validable,habilitable,activo From asignatura";
        ArrayList<String[]> datos = null;
        datos = conexion.consulta(sql);
        DefaultTableModel modelo = (DefaultTableModel)jTableAsignaturas.getModel();
     
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        for(String[] fila : datos){           
            modelo.addRow(fila);
        }
        // hasta aqui
        
        jLCerrar.setToolTipText("Cerrar programa");
        jBEditar.setEnabled(false);
       
        jTCodigoA.setEditable(false);
        jTNombreA.setEditable(false);
        jTNumCreditos.setEditable(false);
        jRNoHabilitable.setEnabled(false);
        jRNoValidable.setEnabled(false);
        jRSiHabilitable.setEnabled(false);
        jRSiValidable.setEnabled(false);
        
        jBEditar.setToolTipText("Solo se podra editar el estado de una asignatura");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLTexto_superior = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLCerrar = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAsignaturas = new javax.swing.JTable();
        jTNombreA = new javax.swing.JTextField();
        jTCodigoA = new javax.swing.JTextField();
        jTTipo = new javax.swing.JTextField();
        jTNumCreditos = new javax.swing.JTextField();
        jLHabilitable = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jRSiHabilitable = new javax.swing.JRadioButton();
        jRInactivo = new javax.swing.JRadioButton();
        jRActivo = new javax.swing.JRadioButton();
        jRNoHabilitable = new javax.swing.JRadioButton();
        jLValidable = new javax.swing.JLabel();
        jRSiValidable = new javax.swing.JRadioButton();
        jRNoValidable = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jTbuscador = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jLNombreA = new javax.swing.JLabel();
        jLCodigoA = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jLNumCreditos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jMenuItem1.setText("heyy");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("jajaja");
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 40, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoUnivalle.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton1.setText("Programas");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 40, 60));

        jLTexto_superior.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLTexto_superior.setForeground(new java.awt.Color(255, 0, 0));
        jLTexto_superior.setText("UNIVERSIDAD DEL VALLE");
        jLTexto_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLTexto_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLTexto_superiorMouseDragged(evt);
            }
        });
        jLTexto_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLTexto_superiorMousePressed(evt);
            }
        });
        getContentPane().add(jLTexto_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 40, 60));

        jButton2.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton2.setText("Facultades");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 40, 60));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jLCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton3.setText("Asignaturas");
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 110, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 40, 60));

        jButton6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, -1));

        jButton5.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton5.setText("Equivalencias");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jTableAsignaturas.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTableAsignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre A", "Codigo A", "Tipo", "Creditos", "Validable", "Habilitable", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAsignaturas.setComponentPopupMenu(jPopupMenu1);
        jTableAsignaturas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableAsignaturas.setGridColor(new java.awt.Color(204, 204, 204));
        jTableAsignaturas.setSelectionBackground(new java.awt.Color(255, 102, 102));
        jTableAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAsignaturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAsignaturas);
        if (jTableAsignaturas.getColumnModel().getColumnCount() > 0) {
            jTableAsignaturas.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableAsignaturas.getColumnModel().getColumn(1).setMaxWidth(200);
            jTableAsignaturas.getColumnModel().getColumn(2).setMaxWidth(110);
            jTableAsignaturas.getColumnModel().getColumn(3).setMaxWidth(110);
            jTableAsignaturas.getColumnModel().getColumn(4).setMaxWidth(120);
            jTableAsignaturas.getColumnModel().getColumn(5).setMaxWidth(120);
            jTableAsignaturas.getColumnModel().getColumn(6).setMaxWidth(60);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 1040, 200));

        jTNombreA.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTNombreA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTNombreA.setOpaque(false);
        getContentPane().add(jTNombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 230, 40));

        jTCodigoA.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTCodigoA.setOpaque(false);
        getContentPane().add(jTCodigoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 230, 40));

        jTTipo.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTTipo.setOpaque(false);
        getContentPane().add(jTTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 230, 40));

        jTNumCreditos.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTNumCreditos.setOpaque(false);
        getContentPane().add(jTNumCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 230, 40));

        jLHabilitable.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLHabilitable.setText("Habilitable");
        getContentPane().add(jLHabilitable, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        jLEstado.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLEstado.setText("Estado");
        getContentPane().add(jLEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, -1, -1));

        jRSiHabilitable.setBackground(new java.awt.Color(255, 255, 255));
        jRSiHabilitable.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRSiHabilitable.setText("Si");
        jRSiHabilitable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSiHabilitableActionPerformed(evt);
            }
        });
        getContentPane().add(jRSiHabilitable, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, -1, -1));

        jRInactivo.setBackground(new java.awt.Color(255, 255, 255));
        jRInactivo.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRInactivo.setText("Inactivo");
        jRInactivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRInactivoActionPerformed(evt);
            }
        });
        getContentPane().add(jRInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, -1, -1));

        jRActivo.setBackground(new java.awt.Color(255, 255, 255));
        jRActivo.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRActivo.setText("Activo");
        jRActivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRActivoActionPerformed(evt);
            }
        });
        getContentPane().add(jRActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, -1, -1));

        jRNoHabilitable.setBackground(new java.awt.Color(255, 255, 255));
        jRNoHabilitable.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRNoHabilitable.setText("No");
        jRNoHabilitable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNoHabilitableActionPerformed(evt);
            }
        });
        getContentPane().add(jRNoHabilitable, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, -1, -1));

        jLValidable.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLValidable.setText("Validable");
        getContentPane().add(jLValidable, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, -1, -1));

        jRSiValidable.setBackground(new java.awt.Color(255, 255, 255));
        jRSiValidable.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRSiValidable.setText("Si");
        jRSiValidable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSiValidableActionPerformed(evt);
            }
        });
        getContentPane().add(jRSiValidable, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, -1, -1));

        jRNoValidable.setBackground(new java.awt.Color(255, 255, 255));
        jRNoValidable.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRNoValidable.setText("No");
        jRNoValidable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNoValidableActionPerformed(evt);
            }
        });
        getContentPane().add(jRNoValidable, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 30, 220));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 30, 220));

        jTbuscador.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbuscadorActionPerformed(evt);
            }
        });
        jTbuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbuscadorKeyReleased(evt);
            }
        });
        getContentPane().add(jTbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 450, 40));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_buscar.png"))); // NOI18N
        jButton8.setToolTipText("");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        jBEditar.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jBEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jBEditar.setText("Editar estado");
        jBEditar.setBorder(null);
        jBEditar.setBorderPainted(false);
        jBEditar.setContentAreaFilled(false);
        jBEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, 190, 50));

        jLNombreA.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLNombreA.setText("Nombre");
        getContentPane().add(jLNombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, -1));

        jLCodigoA.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLCodigoA.setText("Codigo");
        getContentPane().add(jLCodigoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        jLTipo.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLTipo.setText("Tipo");
        getContentPane().add(jLTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 650, -1, -1));

        jLNumCreditos.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLNumCreditos.setText("N° creditos");
        getContentPane().add(jLNumCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recuadro_base.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLTexto_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTexto_superiorMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLTexto_superiorMouseDragged

    private void jLTexto_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTexto_superiorMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jLTexto_superiorMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        // TODO add your handling code here:
       int opcion = JOptionPane.showConfirmDialog(null,"¿Desea salir del programa?");
       if(opcion ==JOptionPane.YES_OPTION) {
        System.exit(0);
       }
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Asignaturas_interfaz asignaturas ;
        asignaturas = new Asignaturas_interfaz();
        asignaturas.setControl(control,datoUsuario);
        this.dispose();
        asignaturas.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         Equivalencias_interfaz equivalencia;
        equivalencia = new Equivalencias_interfaz();
        equivalencia.setControl(control, datoUsuario);
        this.dispose();
        equivalencia.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRSiHabilitableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSiHabilitableActionPerformed
        // TODO add your handling code here:
        if (jRSiHabilitable.isSelected()==true){
            jRNoHabilitable.setEnabled(false);

        }
        else{
            jRNoHabilitable.setEnabled(true);
        }
    }//GEN-LAST:event_jRSiHabilitableActionPerformed

    private void jRInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRInactivoActionPerformed
        // TODO add your handling code here:
        if(jRInactivo.isSelected()){
            jRActivo.setEnabled(false);
        }
        else {
            jRActivo.setEnabled(true);
        }
    }//GEN-LAST:event_jRInactivoActionPerformed

    private void jRActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRActivoActionPerformed
        // TODO add your handling code here:
        if(jRActivo.isSelected()){
            jRInactivo.setEnabled(false);
        }
        else {
            jRInactivo.setEnabled(true);
        }
    }//GEN-LAST:event_jRActivoActionPerformed

    private void jRNoHabilitableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNoHabilitableActionPerformed
        // TODO add your handling code here:
        if (jRNoHabilitable.isSelected()==true){
            jRSiHabilitable.setEnabled(false);

        }
        else{
            jRSiHabilitable.setEnabled(true);
        }
    }//GEN-LAST:event_jRNoHabilitableActionPerformed

    private void jRSiValidableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSiValidableActionPerformed
        // TODO add your handling code here:
        if (jRSiValidable.isSelected()==true){
            jRNoValidable.setEnabled(false);

        }
        else{
            jRNoValidable.setEnabled(true);
        }
    }//GEN-LAST:event_jRSiValidableActionPerformed

    private void jRNoValidableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNoValidableActionPerformed
        // TODO add your handling code here:
        if (jRNoValidable.isSelected()==true){
            jRSiValidable.setEnabled(false);

        }
        else{
            jRSiValidable.setEnabled(true);
        }
    }//GEN-LAST:event_jRNoValidableActionPerformed

    private void jTableAsignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAsignaturasMouseClicked
        // TODO add your handling code here:
         

         int filaSel = jTableAsignaturas.getSelectedRow();
         System.out.println("fila seleccionada:"+filaSel);
         
         DefaultTableModel modelo = (DefaultTableModel)jTableAsignaturas.getModel();
         String nombreA = (String)modelo.getValueAt(filaSel, 0);
         String codigoA = (String)modelo.getValueAt(filaSel, 1);
         String tipo = (String)modelo.getValueAt(filaSel, 2);
         String creditos = (String)modelo.getValueAt(filaSel, 3);
         String validable = (String) modelo.getValueAt(filaSel, 4);
         String habilitable = (String)modelo.getValueAt(filaSel, 5);
         String estado = (String)modelo.getValueAt(filaSel, 6);
       
         System.out.println("validable:"+validable);
         System.out.println("Estado: "+estado);
         
//   modificar.setValues(nombreA,codigoA,Integer.parseInt(creditos),validable,habilitable,estado);
//        this.dispose(); //cierra la ventana   
//       modificar.setVisible(true);
        
        jBEditar.setEnabled(true);
        
        jTNombreA.setText(nombreA);
        jTCodigoA.setText(codigoA);
        jTNumCreditos.setText(creditos);   
        jTTipo.setText(tipo);
        
        jTNombreA.setEnabled(false);
        jTCodigoA.setEnabled(false);
        jTNumCreditos.setEnabled(false);
        jTTipo.setEnabled(false);
        
        if(validable.equals("1")){
            jRSiValidable.setSelected(true);
            jRSiValidable.setEnabled(false);
            jRNoValidable.setEnabled(false);
            jRNoValidable.setSelected(false);
        }
        else {
            jRNoValidable.setEnabled(false);
            jRNoValidable.setSelected(true);
            jRSiValidable.setSelected(false);
            jRSiValidable.setEnabled(false);
            
        }
        if(habilitable.equals("1")){
            jRSiHabilitable.setSelected(true);
            jRSiHabilitable.setEnabled(false);
            jRNoHabilitable.setEnabled(false);
            jRNoHabilitable.setSelected(false);
        }
        else {
            jRNoHabilitable.setEnabled(false);
            jRNoHabilitable.setSelected(true);
            jRSiHabilitable.setSelected(false);
            jRSiHabilitable.setEnabled(false);
            
        }
        if(estado.equals("1")){
            jRActivo.setSelected(true);
            jRActivo.setEnabled(true);
            jRInactivo.setEnabled(false);
            jRInactivo.setSelected(false);
        }
        else {
            jRInactivo.setSelected(true);
            jRInactivo.setEnabled(true);
            jRActivo.setSelected(false);
            jRActivo.setEnabled(false);
           
            
        }
    }//GEN-LAST:event_jTableAsignaturasMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        String dato = jTbuscador.getText();
      
        String sql = "Select nombre,codAsignatura,tipo,numCreditos,validable,habilitable,activo From asignatura where nombre Like '%"+dato+"%' or codAsignatura Like '%"+dato+"%' or tipo Like '%"+dato+"%'";
        ArrayList<String[]> datos = null;
        datos = conexion.consulta(sql);
        DefaultTableModel modelo = (DefaultTableModel)jTableAsignaturas.getModel();
     
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        for(String[] fila : datos){           
            modelo.addRow(fila);
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTbuscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbuscadorKeyReleased
        // TODO add your handling code here:
        String dato = jTbuscador.getText();
        
        String sql = "Select nombre,codAsignatura,tipo,numCreditos,validable,habilitable,activo From asignatura where nombre Like '%"+dato+"%' or codAsignatura Like '%"+dato+"%' or tipo Like '%"+dato+"%'" ;
        ArrayList<String[]> datos = null;
        datos = conexion.consulta(sql);
        DefaultTableModel modelo = (DefaultTableModel)jTableAsignaturas.getModel();
     
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        for(String[] fila : datos){           
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_jTbuscadorKeyReleased

    private void jTbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbuscadorActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
       // try{
//         Modificar_asignatura_interfaz modificar = new Modificar_asignatura_interfaz();
//         int filaSel = jTableAsignaturas.getSelectedRow();
//         System.out.println(filaSel);
//         
//         DefaultTableModel modelo = (DefaultTableModel)jTableAsignaturas.getModel();
//          String nombreA = (String)modelo.getValueAt(filaSel, 0);
//         String codigoA = (String)modelo.getValueAt(filaSel, 1);
//         String creditos = (String)modelo.getValueAt(filaSel, 2);
//         String validable = (String)modelo.getValueAt(filaSel, 3);
//         String habilitable = (String)modelo.getValueAt(filaSel, 4);
//         String estado = (String)modelo.getValueAt(filaSel, 5);
//
//       modificar.setValues(nombreA,codigoA,Integer.parseInt(creditos),validable,habilitable,estado);
//        this.dispose(); //cierra la ventana   
//       modificar.setVisible(true);
//        
//         }
//         catch(Exception a2){
//         JOptionPane.showMessageDialog(this,"\"Debe seleccionar una fila de la consulta primero \nantes de editar\"");
//         }
       if(jRActivo.isSelected()!=false || jRInactivo.isSelected()!=false){
           
       int opcion = JOptionPane.showConfirmDialog(null,"¿Esta seguro que desea editar el estado de la asignatura?");
       
       if(opcion ==JOptionPane.YES_OPTION){
      try{
        String estado ="0";
        String codigoA= jTCodigoA.getText();
        
        if(jRActivo.isSelected()){
            estado="1";
        }
        
        String sql  ="UPDATE asignatura SET activo= '"+estado+"' WHERE codAsignatura='"+codigoA+"'";
        
        conexion.sentencia(sql);
       }
       catch(Exception ex){
           JOptionPane.showMessageDialog(this,ex);
       }
       }
       }
       else{
           JOptionPane.showMessageDialog(this,"Porfavor marque una opcion si desea editar la asignatura");
       }
    }//GEN-LAST:event_jBEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar_editar_asignaturas_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar_editar_asignaturas_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar_editar_asignaturas_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar_editar_asignaturas_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                   try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); //hace parte de lo del marco de la interfaz
                    
                } catch (Exception ex) {
                    System.out.println("Error de recuadro interfaz");
                } 
                new Consultar_editar_asignaturas_interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLCodigoA;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLHabilitable;
    private javax.swing.JLabel jLNombreA;
    private javax.swing.JLabel jLNumCreditos;
    private javax.swing.JLabel jLTexto_superior;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLValidable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRActivo;
    private javax.swing.JRadioButton jRInactivo;
    private javax.swing.JRadioButton jRNoHabilitable;
    private javax.swing.JRadioButton jRNoValidable;
    private javax.swing.JRadioButton jRSiHabilitable;
    private javax.swing.JRadioButton jRSiValidable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTCodigoA;
    private javax.swing.JTextField jTNombreA;
    private javax.swing.JTextField jTNumCreditos;
    private javax.swing.JTextField jTTipo;
    private javax.swing.JTable jTableAsignaturas;
    private javax.swing.JTextField jTbuscador;
    // End of variables declaration//GEN-END:variables
}
