/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homologaciones;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author JOHN EDWAR
 */
public class Login_univalle extends javax.swing.JFrame {


    private int x,y; //variables para el control de la posicion del login al mover con el mouse
    private int control;
    private String sql="";
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Login_univalle() throws ClassNotFoundException {
        
        con  = conexionBD.newconexion();
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        
        TextPrompt usuario = new TextPrompt(" Usuario", JTUsuario);
        TextPrompt contraseña = new TextPrompt(" Contraseña", jTContraseña);
        
        JTUsuario.setToolTipText("codigo si es estudiante o cedula si es gestor");
        
        jLEstudiante.setToolTipText("Estudiante");
        jLGestor.setToolTipText("Gestor");
        jLCerrar.setToolTipText("Cerrar programa");
    }
    
    public void Loguear() throws ClassNotFoundException{
       
        UIManager UI=new UIManager(); // para cambiar el color de fondo de los JOptionpane
        UI.put("OptionPane.background",Color.white);
        UI.put("Panel.background",Color.white);  

        
       try{
           pst = con.prepareStatement(sql);
          
           pst.setInt(1, Integer.parseInt(JTUsuario.getText())); // en el primer signo de pregunta se pone lo que hay en el jText
           
           pst.setString(2, jTContraseña.getText()); //  en el segundo signo de pregunta se pone lo que hay en el jText
           
           rs = pst.executeQuery();
           
           if(rs.next()){              

                   Interfaz_principal interfazP = new Interfaz_principal();
                   interfazP.setValor(control,Integer.parseInt(JTUsuario.getText()));
                   this.dispose();
                   
                   interfazP.setVisible(true);

           }else{
               
               JOptionPane.showMessageDialog(null, "usuario y contraseña inválidos");
           }
           
       }catch(Exception error){
       
//         JOptionPane.showMessageDialog(null, error);
           JOptionPane.showMessageDialog(null, "Verfique que todos los campos esten diligenciados");
           
       
       }
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtexto_superior = new javax.swing.JLabel();
        jLCerrar = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jREstudiante = new javax.swing.JRadioButton();
        jRGestor = new javax.swing.JRadioButton();
        JTUsuario = new javax.swing.JTextField();
        jTContraseña = new javax.swing.JPasswordField();
        jLEstudiante = new javax.swing.JLabel();
        jLGestor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLtexto_superior.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLtexto_superior.setForeground(new java.awt.Color(255, 0, 0));
        jLtexto_superior.setText("INICIAR SESION");
        jLtexto_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLtexto_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLtexto_superiorMouseDragged(evt);
            }
        });
        jLtexto_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLtexto_superiorMousePressed(evt);
            }
        });
        getContentPane().add(jLtexto_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 180, 30));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jLCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jButton3.setText("Registrarse");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 170, 60));

        jButton4.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jButton4.setText("Ingresar");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 170, 60));

        jLabel9.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Olvide mi contraseña");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoUsuario.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 60, 50));

        jLabel10.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Cambiar contraseña");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoContraseña.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 60, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Desarrollado por @JCCBAVSG");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 690, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 420, 20));

        jREstudiante.setBackground(new java.awt.Color(255, 255, 255));
        jREstudiante.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jREstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jREstudianteMouseClicked(evt);
            }
        });
        jREstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jREstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jREstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 30, -1));

        jRGestor.setBackground(new java.awt.Color(255, 255, 255));
        jRGestor.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRGestor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRGestorMouseClicked(evt);
            }
        });
        jRGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRGestorActionPerformed(evt);
            }
        });
        getContentPane().add(jRGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 30, -1));

        JTUsuario.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        JTUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTUsuarioActionPerformed(evt);
            }
        });
        JTUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(JTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 250, 50));

        jTContraseña.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jTContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 250, 50));

        jLEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoEstudiante.png"))); // NOI18N
        getContentPane().add(jLEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 50, 60));

        jLGestor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconoMaestro.png"))); // NOI18N
        getContentPane().add(jLGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1110, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTUsuarioActionPerformed

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        // TODO add your handling code here:
       int opcion = JOptionPane.showConfirmDialog(null,"¿Desea salir del programa?");
       if(opcion ==JOptionPane.YES_OPTION) {
        System.exit(0);
       }
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jLtexto_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLtexto_superiorMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jLtexto_superiorMousePressed

    private void jLtexto_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLtexto_superiorMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLtexto_superiorMouseDragged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     
     if ( !jTContraseña.getText().equals("") && !JTUsuario.getText().equals("")){
         
        if(control!=0){   
           try {
               Loguear();
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(Login_univalle.class.getName()).log(Level.SEVERE, null, ex);
              
           }
        }
        else{
            JOptionPane.showMessageDialog(null, "Porfavor marque si es estudiante o gestor", "Mensaje informativo", JOptionPane.INFORMATION_MESSAGE);
     }
     }
     else{
          JOptionPane.showMessageDialog(null, "Verifique que todos los campos esten diligenciados", "Mensaje informativo", JOptionPane.INFORMATION_MESSAGE);

     }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Registrar_usuarios_interfaz registro = new Registrar_usuarios_interfaz();
        
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jREstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jREstudianteActionPerformed
        // TODO add your handling code here:
        if (jREstudiante.isSelected()==true){
            jRGestor.setEnabled(false);
            control=1;
            sql = "select codFicha, contraseña from estudiante A, ficha B where  B.codFicha= ? and A.contraseña = ? and A.cedula = B.cedula";
        }
        else{
             jRGestor.setEnabled(true);
             control=0;
        }
    }//GEN-LAST:event_jREstudianteActionPerformed

    private void jRGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRGestorActionPerformed
        // TODO add your handling code here:
        if (jRGestor.isSelected()==true){
            jREstudiante.setEnabled(false);
            control=2;
            sql = "select cedula, contraseña from gestor where cedula = ? and contraseña = ? ";
        }
        else{
            jREstudiante.setEnabled(true);
            control=0;
        }
    }//GEN-LAST:event_jRGestorActionPerformed

    private void jREstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jREstudianteMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jREstudianteMouseClicked

    private void jRGestorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRGestorMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jRGestorMouseClicked

    private void JTUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTUsuarioKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar(); // KeyChar Obtiene o establece el carácter correspondiente a la tecla presionada.
       
       if(n<'0' || n>'9'){
           evt.consume();
       }
    }//GEN-LAST:event_JTUsuarioKeyTyped

    private void jTContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_univalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_univalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_univalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_univalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                }
                try {
                    new Login_univalle().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Login_univalle.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTUsuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLEstudiante;
    private javax.swing.JLabel jLGestor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLtexto_superior;
    private javax.swing.JRadioButton jREstudiante;
    private javax.swing.JRadioButton jRGestor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField jTContraseña;
    // End of variables declaration//GEN-END:variables
}
