/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homologaciones;

import com.sun.awt.AWTUtilities;
import static homologaciones.Agregar_Asignatura.Tabla_Agregar;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Spring;
import javax.swing.UIManager;
import java.awt.*;
import java.awt.print.*;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Cristian
 */
public class Registro_equivalencia_otra_universidad extends javax.swing.JFrame  {

    /**
     * Creates new form Registro_equivalencia_otra_universidad
     */
    
    int x,y;
    int controlP=0;
    int datousuario=0;
    int Max=0;
    
   

    String estado= "Pendiente";
    conexionBD conexion = new conexionBD();
   
  
    public void setControl(int valor, int dato){
        controlP=valor;
        datousuario=dato;

        // jCProgramaDestino.addItem( String.valueOf(datousuario));
        System.out.println("dentro del set: "+valor+","+controlP);
        System.out.println("cmon puto"+datousuario);
        
      

        String sql3= "select A.nombre , B.cedula from estudiante A, ficha B where B.codficha='"+datousuario+"' and A.cedula=B.cedula ";   
        ArrayList<String[]> datos2 = conexion.consulta(sql3); 
        for(int i=0; i<datos2.size(); i++){           
            System.out.println("fila: " + datos2.get(i).toString());
            
            String [] auxiliar =datos2.get(i); // me trae el primer arreglo del arraylist en esta variable auxiliar
          
            
            for (int j = 0; j < auxiliar.length; j++) {
                
                String dato3 = auxiliar[0];
                String dato4 = auxiliar[1];
              
                
               Cedula.setText(dato4);
               Nombre.setText(dato3);
            }   
        }
        
            
    }
            
    public Registro_equivalencia_otra_universidad() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
       jBEnviarSolicitud.setEnabled(false);
       
          String sql2= "select nombre from universidad ";
        ArrayList<String[]> datos1 = conexion.consulta(sql2);
        
         jCUniversidadOrigen.removeAllItems();
        
         jCUniversidadOrigen.addItem("Universidad origen");
          for(int i=0; i<datos1.size(); i++){           
            System.out.println("fila: " + datos1.get(i).toString());
            
            String [] auxiliar =datos1.get(i); // me trae el primer arreglo del arraylist en esta variable auxiliar
          
            
            for (int j = 0; j < auxiliar.length; j++) {
                
                String dato2 = auxiliar[j];
              
                
               jCUniversidadOrigen.addItem(dato2);
            
            }   
        }
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLTexto_superior = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLCerrar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCUniversidadOrigen = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTAsignaturas = new javax.swing.JTable();
        jBEnviarSolicitud = new javax.swing.JButton();
        jBAgregarAsignatura = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono cerrar sesion.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, 60, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 40, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoUnivalle.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton1.setText("Programas");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 40, 60));

        jLTexto_superior.setFont(new java.awt.Font("Open Sans", 0, 30)); // NOI18N
        jLTexto_superior.setForeground(new java.awt.Color(255, 0, 0));
        jLTexto_superior.setText("UNIVERSIDAD DEL VALLE");
        jLTexto_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLTexto_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLTexto_superiorMouseDragged(evt);
            }
        });
        jLTexto_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLTexto_superiorMousePressed(evt);
            }
        });
        getContentPane().add(jLTexto_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jButton2.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton2.setText("Facultades");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 40, 60));

        jButton3.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton3.setText("Asignaturas");
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 110, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 40, 60));

        jButton6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, -1));

        jButton5.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton5.setText("Equivalencias");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jLCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 40, 60));

        Nombre.setBackground(new java.awt.Color(250, 250, 250));
        Nombre.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        Nombre.setEnabled(false);
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 200, 30));

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        Cedula.setBackground(new java.awt.Color(250, 250, 250));
        Cedula.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        Cedula.setEnabled(false);
        getContentPane().add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 160, 30));

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel3.setText("Cedula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        jCUniversidadOrigen.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jCUniversidadOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCUniversidadOrigenActionPerformed(evt);
            }
        });
        getContentPane().add(jCUniversidadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 310, 30));

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel8.setText("Universidad Origen");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        JTAsignaturas.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        JTAsignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO ASIGNATURA", "NOMBRE", "NOTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JTAsignaturas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 980, 220));

        jBEnviarSolicitud.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jBEnviarSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        jBEnviarSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jBEnviarSolicitud.setText("Enviar solicitud");
        jBEnviarSolicitud.setBorder(null);
        jBEnviarSolicitud.setBorderPainted(false);
        jBEnviarSolicitud.setContentAreaFilled(false);
        jBEnviarSolicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEnviarSolicitud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBEnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(jBEnviarSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 200, 50));

        jBAgregarAsignatura.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jBAgregarAsignatura.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jBAgregarAsignatura.setText("Agregar asignaturas");
        jBAgregarAsignatura.setBorder(null);
        jBAgregarAsignatura.setBorderPainted(false);
        jBAgregarAsignatura.setContentAreaFilled(false);
        jBAgregarAsignatura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregarAsignatura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAgregarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarAsignaturaActionPerformed(evt);
            }
        });
        getContentPane().add(jBAgregarAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 200, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recuadro_base.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLTexto_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTexto_superiorMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLTexto_superiorMouseDragged

    private void jLTexto_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTexto_superiorMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jLTexto_superiorMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setFont(new Font("Arial",Font.PLAIN,30));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Asignaturas_interfaz asignaturas ;

        asignaturas = new Asignaturas_interfaz();
        asignaturas.setControl(controlP,datousuario);
        this.dispose();
        asignaturas.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null,"¿Desea salir del programa?");
        if(opcion ==JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jCUniversidadOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCUniversidadOrigenActionPerformed
        // TODO add your handling code here:
        if(jCUniversidadOrigen.getSelectedIndex()!=0){
            jBEnviarSolicitud.setEnabled(true);
        }
        else{
            jBEnviarSolicitud.setEnabled(false);
        }
        System.out.println(jCUniversidadOrigen.getSelectedItem());
    }//GEN-LAST:event_jCUniversidadOrigenActionPerformed

    private void jBAgregarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarAsignaturaActionPerformed
        // TODO add your handling code here:
        Agregar_Asignatura agregar = new Agregar_Asignatura();
        agregar.setVisible(true);
        agregar.setControl(controlP,datousuario );

    
        TableModel modelo2= JTAsignaturas.getModel();
        
       Agregar_Asignatura.Tabla_Agregar.setModel(modelo2);
        this.dispose();
       
        
    }//GEN-LAST:event_jBAgregarAsignaturaActionPerformed

    private void jBEnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarSolicitudActionPerformed
        // TODO add your handling code here:
        int opciones = JOptionPane.showConfirmDialog(null,"¿Desea enviar la solicitud?");
        if (opciones ==JOptionPane.YES_OPTION){
            
            Calendar fecha= new GregorianCalendar();  
        String fechaActual=fecha.get(Calendar.DATE)+ "-"+(fecha.get(Calendar.MONTH)+1)+"-"+fecha.get(Calendar.YEAR);
       //-----------------------------------------
       String nombrePersona="";

        String sql2="select B.nombre from ficha A, estudiante B where A.codFicha='"+datousuario+"' and A.cedula = B.cedula "; // sentencia apra obetner el nombe de la persona que hace la solicitud
        ArrayList<String[]> datos1 = conexion.consulta(sql2);
   
        // for para la segunda consulta
         for(int i=0; i<datos1.size(); i++){           
            System.out.println("fila: " + datos1.get(i).toString());
            
            String [] auxiliar =datos1.get(i); // me trae el primer arreglo del arraylist en esta variable auxiliar
            nombrePersona=auxiliar[i];
        }
       //------------------------------------------
          //-----------------------------------------
       String programaDestino="";

        String sql3="select codPrograma from ficha where codFicha='"+datousuario+"'"; // sentencia apra obetner el nombe de la persona que hace la solicitud
        ArrayList<String[]> datos2 = conexion.consulta(sql3);
   
        // for para la segunda consulta
         for(int i=0; i<datos2.size(); i++){           
            System.out.println("fila: " + datos2.get(i).toString());
            
            String [] auxiliar =datos2.get(i); // me trae el primer arreglo del arraylist en esta variable auxiliar
            programaDestino=auxiliar[i];
        }
       //------------------------------------------    
        String sql4="insert into solicitud (estado,codFicha, nombre,iduniversidad,fecha,codProgramaDestino) values('"+estado+"','"+datousuario+"','"+nombrePersona+"', '"+jCUniversidadOrigen.getSelectedIndex()+"','"+fechaActual+"','"+Integer.parseInt(programaDestino)+"')";
        conexion.sentencia(sql4);
        
          String sql="select max (numSolicitud) from solicitud";
     
      ArrayList<String[]> max = conexion.consulta(sql);
        String d=null;
        for(int i=0; i<max.size(); i++){           
                       
            String [] auxiliar =max.get(i); // me trae el primer arreglo del arraylist en esta variable auxiliar
            d=auxiliar[i];
            
            if(d!=null){
                Max =Integer.parseInt(d);
            }
            else{
                Max+=1;
            }
             System.out.println("el valor maximo es "+Max);
            
        }
        
        String sql5="insert into solicitudDetalle (numSolicitud,codAsignatura,nombre,nota) values";
        
        //para agregar la solicitud detalle
         for (int i = 0; i < JTAsignaturas.getRowCount(); i++) {
             System.out.println("i= "+ i);
             
            for (int j = 0; j < JTAsignaturas.getColumnCount(); j++) {
                           

                if(j==0){
                 sql5+="('"+Max+"'"+", "+"'"+JTAsignaturas.getValueAt(i, j)+"'";
                }
                else if(i==(JTAsignaturas.getRowCount()-1) && j==(JTAsignaturas.getColumnCount()-1)){
                    sql5+=", "+"'"+JTAsignaturas.getValueAt(i, j)+"'"+ ")";
                }
                else if(j==(JTAsignaturas.getColumnCount()-1)){
                    sql5+=", "+"'"+JTAsignaturas.getValueAt(i, j)+"'"+ "),";
                }
                else{
                    sql5+=","+"'"+JTAsignaturas.getValueAt(i, j)+"'";
                }
                  System.out.println("j= "+ i);
            }
            
            
        }
                 
//      System.out.println("sql final: "+ sql4);
        conexion.sentencia(sql5);
        DefaultTableModel modelo = (DefaultTableModel) JTAsignaturas.getModel();
            while(modelo.getRowCount()>0)modelo.removeRow(0);

     }
    }//GEN-LAST:event_jBEnviarSolicitudActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null,"¿Desea cerrar sesion?");
        if(opcion ==JOptionPane.YES_OPTION) {
            try {
                Login_univalle log = new Login_univalle();
                this.dispose();
                log.setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Interfaz_principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(tring args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro_equivalencia_otra_universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro_equivalencia_otra_universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro_equivalencia_otra_universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro_equivalencia_otra_universidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); //hace parte de lo del marco de la interfaz
//                    
//                } catch (Exception ex) {
//                    System.out.println("Error de recuadro interfaz");
//                } 
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cedula;
    public static javax.swing.JTable JTAsignaturas;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton jBAgregarAsignatura;
    private javax.swing.JButton jBEnviarSolicitud;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jCUniversidadOrigen;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLTexto_superior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables

  

   

  
}
