/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homologaciones;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import rojerusan.RSNotifyAnimated;
import rojerusan.RSNotifyFade;

/**
 *
 * @author JOHN EDWAR
 */
public class Registrar_asignaturas_interfaz  extends javax.swing.JFrame  {

    /**
     * Creates new form Registrar_asignaturas_interfaz
     */
    int x,y;
    int control=0;
    int datoUsuario;
    
    public Registrar_asignaturas_interfaz() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        
        jButton4.setToolTipText("Haga click aqui para registrar");
        
        jLCerrar.setToolTipText("Cerrar programa");
        
        UIManager UI=new UIManager(); // para cambiar el color de fondo de los JOptionpane
        UI.put("OptionPane.background",Color.white);
        UI.put("Panel.background",Color.white);  
    }
     public void setControl(int controlP,int dato) {
        
            datoUsuario=dato;
            control=controlP;        
     }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLTexto_superior = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTNumCreditos = new javax.swing.JTextField();
        jTCodigoA = new javax.swing.JTextField();
        jLCerrar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRSiHabilitable = new javax.swing.JRadioButton();
        jRInactivo = new javax.swing.JRadioButton();
        jRActivo = new javax.swing.JRadioButton();
        jRNoHabilitable = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRSiValidable = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jRNoValidable = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jTNombreA = new javax.swing.JTextField();
        jTTipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono cerrar sesion.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, 60, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 40, 60));

        jButton1.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton1.setText("Programas");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 40, 60));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 40, 60));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 40, 60));

        jButton5.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton5.setText("Equivalencias");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jButton3.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton3.setText("Asignaturas");
        jButton3.setToolTipText("");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jButton6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 40, 60));

        jButton2.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        jButton2.setText("Facultades");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLTexto_superior.setFont(new java.awt.Font("Open Sans", 0, 30)); // NOI18N
        jLTexto_superior.setForeground(new java.awt.Color(255, 0, 0));
        jLTexto_superior.setText("UNIVERSIDAD DEL VALLE");
        jLTexto_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLTexto_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLTexto_superiorMouseDragged(evt);
            }
        });
        jLTexto_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLTexto_superiorMousePressed(evt);
            }
        });
        getContentPane().add(jLTexto_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoUnivalle.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTNumCreditos.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTNumCreditos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNumCreditos.setOpaque(false);
        jTNumCreditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNumCreditosKeyTyped(evt);
            }
        });
        getContentPane().add(jTNumCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 240, 40));

        jTCodigoA.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTCodigoA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTCodigoA.setOpaque(false);
        getContentPane().add(jTCodigoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 240, 40));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jLCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel8.setText("Habilitable");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel10.setText("Estado");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, -1, -1));

        jRSiHabilitable.setBackground(new java.awt.Color(255, 255, 255));
        jRSiHabilitable.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRSiHabilitable.setText("Si");
        jRSiHabilitable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSiHabilitableActionPerformed(evt);
            }
        });
        getContentPane().add(jRSiHabilitable, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        jRInactivo.setBackground(new java.awt.Color(255, 255, 255));
        jRInactivo.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRInactivo.setText("Inactivo");
        jRInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRInactivoActionPerformed(evt);
            }
        });
        getContentPane().add(jRInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, -1, -1));

        jRActivo.setBackground(new java.awt.Color(255, 255, 255));
        jRActivo.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRActivo.setText("Activo");
        jRActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRActivoActionPerformed(evt);
            }
        });
        getContentPane().add(jRActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, -1, -1));

        jRNoHabilitable.setBackground(new java.awt.Color(255, 255, 255));
        jRNoHabilitable.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRNoHabilitable.setText("No");
        jRNoHabilitable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNoHabilitableActionPerformed(evt);
            }
        });
        getContentPane().add(jRNoHabilitable, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        jLabel9.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel9.setText("Validable");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, -1, -1));

        jRSiValidable.setBackground(new java.awt.Color(255, 255, 255));
        jRSiValidable.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRSiValidable.setText("Si");
        jRSiValidable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSiValidableActionPerformed(evt);
            }
        });
        getContentPane().add(jRSiValidable, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 890, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 880, 30));

        jRNoValidable.setBackground(new java.awt.Color(255, 255, 255));
        jRNoValidable.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jRNoValidable.setText("No");
        jRNoValidable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNoValidableActionPerformed(evt);
            }
        });
        getContentPane().add(jRNoValidable, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        jButton4.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton2_colorMarca.png"))); // NOI18N
        jButton4.setText("Registrar");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 630, -1, -1));

        jLNombre.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLNombre.setText("Codigo");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jTNombreA.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTNombreA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNombreA.setOpaque(false);
        getContentPane().add(jTNombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 240, 40));

        jTTipo.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jTTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTTipo.setOpaque(false);
        jTTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTTipoKeyTyped(evt);
            }
        });
        getContentPane().add(jTTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 240, 40));

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel2.setText("Nombre ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel5.setText("N° creditos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recuadro_base.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         Equivalencias_interfaz equivalencia;
        equivalencia = new Equivalencias_interfaz();
        equivalencia.setControl(control,datoUsuario);
        this.dispose();
        equivalencia.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Asignaturas_interfaz asignaturas ;

        asignaturas = new Asignaturas_interfaz();
        this.dispose();
        asignaturas.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLTexto_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTexto_superiorMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLTexto_superiorMouseDragged

    private void jLTexto_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTexto_superiorMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jLTexto_superiorMousePressed

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null,"¿Desea salir del programa?");
       if(opcion ==JOptionPane.YES_OPTION) {
        System.exit(0);
       };
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jRNoHabilitableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNoHabilitableActionPerformed
        // TODO add your handling code here:
         if (jRNoHabilitable.isSelected()==true){
            jRSiHabilitable.setEnabled(false);
           
        }
        else{
            jRSiHabilitable.setEnabled(true);
        }
    }//GEN-LAST:event_jRNoHabilitableActionPerformed

    private void jRNoValidableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNoValidableActionPerformed
        // TODO add your handling code here:
         if (jRNoValidable.isSelected()==true){
            jRSiValidable.setEnabled(false);
           
        }
        else{
            jRSiValidable.setEnabled(true);
        }
    }//GEN-LAST:event_jRNoValidableActionPerformed

    private void jRSiHabilitableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSiHabilitableActionPerformed
        // TODO add your handling code here:
        if (jRSiHabilitable.isSelected()==true){
            jRNoHabilitable.setEnabled(false);
           
        }
        else{
            jRNoHabilitable.setEnabled(true);
        }
    }//GEN-LAST:event_jRSiHabilitableActionPerformed

    private void jRSiValidableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSiValidableActionPerformed
        // TODO add your handling code here:
         if (jRSiValidable.isSelected()==true){
            jRNoValidable.setEnabled(false);
           
        }
        else{
            jRNoValidable.setEnabled(true);
        }
    }//GEN-LAST:event_jRSiValidableActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.out.println("seleccion "+ jRActivo.isSelected());
     if(!jTCodigoA.getText().equals("") && !jTCodigoA.getText().equals("") && (jRActivo.isSelected()!=false || jRInactivo.isEnabled()!=false) && (jRNoHabilitable.isSelected()!=false ||jRSiHabilitable.isSelected()!=false) && (jRNoValidable.isSelected()!=false || jRSiValidable.isSelected()!=false) &&(jRActivo.isSelected()!=false || jRInactivo.isSelected()!=false) ){ 
         int opcion = JOptionPane.showConfirmDialog(null,"¿Esta seguro que desea registrar la asignatura?");
       if(opcion ==JOptionPane.YES_OPTION) {
           try {     
            String nombreA = jTNombreA.getText();
            String codigoA = jTCodigoA.getText();
            int numCreditos = Integer.parseInt(jTNumCreditos.getText());
            String tipo = jTTipo.getText();
            String opcionHabilitable = "0";
            String opcionValidable = "0";     
            String opcionEstado ="0";
            
            if (jRSiHabilitable.isSelected()){
                 opcionHabilitable = "1";
            }
             if (jRSiValidable.isSelected()){
                 opcionValidable = "1";
            }
            if (jRActivo.isSelected()){
                opcionEstado="1";
            } 
            
            String sql = "insert into asignatura (codAsignatura,nombre,numCreditos,tipo,validable,habilitable,activo) values ('"+codigoA+"','"+nombreA+"','"+numCreditos+"','"+tipo+"','"+opcionValidable+"','"+opcionHabilitable+"','"+opcionEstado+"')";
            conexionBD con = new conexionBD();
       
            
            jTCodigoA.setText("");
            jTNombreA.setText("");
            jTNumCreditos.setText("");
            jTTipo.setText("");
            
            con.sentencia(sql);
           
                       
        } catch (Exception ex) {
            
            System.out.println("error aqui cuando presione el boton ");
            JOptionPane.showMessageDialog(null, "Verifique que los campos no esten vacios","Campos vacios" ,JOptionPane.INFORMATION_MESSAGE);

        }
       };
         
     }
     else{
         JOptionPane.showMessageDialog(null, "Verifique que los campos no esten vacios","Campos vacios" ,JOptionPane.INFORMATION_MESSAGE);
     }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRInactivoActionPerformed
        // TODO add your handling code here:
        if(jRInactivo.isSelected()){
            jRActivo.setEnabled(false);
        }
        else {
            jRActivo.setEnabled(true);
        }
    }//GEN-LAST:event_jRInactivoActionPerformed

    private void jRActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRActivoActionPerformed
        // TODO add your handling code here:
        if(jRActivo.isSelected()){
            jRInactivo.setEnabled(false);
        }
        else {
            jRInactivo.setEnabled(true);
        }
    }//GEN-LAST:event_jRActivoActionPerformed

    private void jTNumCreditosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNumCreditosKeyTyped
        // TODO add your handling code here:
         char n = evt.getKeyChar(); // KeyChar Obtiene o establece el carácter correspondiente a la tecla presionada.
       
       if(n<'0' || n>'9'){
           evt.consume();
       }
    }//GEN-LAST:event_jTNumCreditosKeyTyped

    private void jTTipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTipoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTipoKeyTyped

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null,"¿Desea cerrar sesion?");
        if(opcion ==JOptionPane.YES_OPTION) {
            try {
                Login_univalle log = new Login_univalle();
                this.dispose();
                log.setVisible(true);
            } catch (ClassNotFoundException ex) {
                
            }

        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registrar_asignaturas_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registrar_asignaturas_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registrar_asignaturas_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registrar_asignaturas_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                 try {
//                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); //hace parte de lo del marco de la interfaz
//                    
//                } catch (Exception ex) {
//                    System.out.println("Error de recuadro interfaz");
//                } 
//                
//                new Registrar_asignaturas_interfaz().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTexto_superior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRActivo;
    private javax.swing.JRadioButton jRInactivo;
    private javax.swing.JRadioButton jRNoHabilitable;
    private javax.swing.JRadioButton jRNoValidable;
    private javax.swing.JRadioButton jRSiHabilitable;
    private javax.swing.JRadioButton jRSiValidable;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTCodigoA;
    private javax.swing.JTextField jTNombreA;
    private javax.swing.JTextField jTNumCreditos;
    private javax.swing.JTextField jTTipo;
    // End of variables declaration//GEN-END:variables
}
