/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homologaciones;

import com.sun.awt.AWTUtilities;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author JOHN EDWAR
 */
public class solicitud_interfaz extends javax.swing.JFrame {

    /**
     * Creates new form solicitud_interfaz
     */
    int x,y;
    
    public solicitud_interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLlogo_univalle = new javax.swing.JLabel();
        jLtexto_superior = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTcual = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCotra = new javax.swing.JCheckBox();
        jCcambio = new javax.swing.JCheckBox();
        jCtraslado = new javax.swing.JCheckBox();
        jCtransferencia = new javax.swing.JCheckBox();
        jCmodificacion = new javax.swing.JCheckBox();
        jCreingreso = new javax.swing.JCheckBox();
        jCreingreso_traslado = new javax.swing.JCheckBox();
        jLcual = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLlogo_univalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/este si es.png"))); // NOI18N
        getContentPane().add(jLlogo_univalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 80));

        jLtexto_superior.setFont(new java.awt.Font("Century Schoolbook", 0, 26)); // NOI18N
        jLtexto_superior.setForeground(new java.awt.Color(255, 255, 255));
        jLtexto_superior.setText("Solicitud equivalencias");
        jLtexto_superior.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLtexto_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLtexto_superiorMouseDragged(evt);
            }
        });
        jLtexto_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLtexto_superiorMousePressed(evt);
            }
        });
        getContentPane().add(jLtexto_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 330, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar_32px.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, -1, -1));

        jTextField1.setBackground(new java.awt.Color(224, 220, 220));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 250, 30));

        jLabel2.setText("Nombre y apellidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 40));

        jLabel3.setText("Codigo Estudiante");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jTextField2.setBackground(new java.awt.Color(224, 220, 220));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 250, 30));

        jLabel5.setText("Nombre programa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel6.setText("Codigo programa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jTextField3.setBackground(new java.awt.Color(224, 220, 220));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 250, 30));

        jTcual.setBackground(new java.awt.Color(224, 220, 220));
        getContentPane().add(jTcual, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 250, 30));

        jTextField5.setBackground(new java.awt.Color(224, 220, 220));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 250, 30));

        jLabel7.setText("Celular");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel8.setText("Correo electronico");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jTextField6.setBackground(new java.awt.Color(224, 220, 220));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 250, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("RAZON DE LA EQUIVALENCIA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, -1, -1));

        jCotra.setBackground(new java.awt.Color(255, 255, 255));
        jCotra.setText(" Otra");
        jCotra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCotraActionPerformed(evt);
            }
        });
        getContentPane().add(jCotra, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        jCcambio.setBackground(new java.awt.Color(255, 255, 255));
        jCcambio.setText(" Por cambio de especial a regular");
        jCcambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcambioActionPerformed(evt);
            }
        });
        getContentPane().add(jCcambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, -1, -1));

        jCtraslado.setBackground(new java.awt.Color(255, 255, 255));
        jCtraslado.setText(" Por traslado");
        jCtraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtrasladoActionPerformed(evt);
            }
        });
        getContentPane().add(jCtraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        jCtransferencia.setBackground(new java.awt.Color(255, 255, 255));
        jCtransferencia.setText(" Por transferencia");
        jCtransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtransferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jCtransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));

        jCmodificacion.setBackground(new java.awt.Color(255, 255, 255));
        jCmodificacion.setText(" Por modificacion de curriculo");
        jCmodificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmodificacionActionPerformed(evt);
            }
        });
        getContentPane().add(jCmodificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        jCreingreso.setBackground(new java.awt.Color(255, 255, 255));
        jCreingreso.setText(" Por reingreso");
        jCreingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreingresoActionPerformed(evt);
            }
        });
        getContentPane().add(jCreingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jCreingreso_traslado.setBackground(new java.awt.Color(255, 255, 255));
        jCreingreso_traslado.setText(" Por reingreso con traslado");
        jCreingreso_traslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreingreso_trasladoActionPerformed(evt);
            }
        });
        getContentPane().add(jCreingreso_traslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, -1, -1));

        jLcual.setText("Cual");
        getContentPane().add(jLcual, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 40, -1));

        jTextField7.setBackground(new java.awt.Color(224, 220, 220));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 250, 30));

        jButton1.setText("Ingresar asignaturas");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 220, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("DATOS ESTUDIANTE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Calif"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 1050, 180));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/interfaz_solicitud.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLtexto_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLtexto_superiorMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLtexto_superiorMouseDragged

    private void jLtexto_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLtexto_superiorMousePressed
        // TODO add your handling code here:
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jLtexto_superiorMousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Interfaz_principal crear;
        try {
            crear = new Interfaz_principal();
            this.setVisible(false);
            crear.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(solicitud_interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jCotraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCotraActionPerformed
        // TODO add your handling code here:
        if(jCotra.isSelected()==true){
        jCcambio.setEnabled(false);
        jCmodificacion.setEnabled(false);
        jCtransferencia.setEnabled(false);
        jCreingreso.setEnabled(false);
        jCreingreso_traslado.setEnabled(false);
        jCtraslado.setEnabled(false);
        }
        else{
        jCcambio.setEnabled(true);
        jCmodificacion.setEnabled(true);
        jCtransferencia.setEnabled(true);
        jCreingreso.setEnabled(true);
        jCreingreso_traslado.setEnabled(true);
        jCtraslado.setEnabled(true);

        }
    }//GEN-LAST:event_jCotraActionPerformed

    private void jCmodificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmodificacionActionPerformed
        // TODO add your handling code here:
        if(jCmodificacion.isSelected()==true){
        jCcambio.setEnabled(false);
        jCtransferencia.setEnabled(false);
        jCotra.setEnabled(false);
        jCreingreso.setEnabled(false);
        jCreingreso_traslado.setEnabled(false);
        jCtraslado.setEnabled(false);
        jTcual.setEnabled(false);
        }
        else{
        jCcambio.setEnabled(true);
        jCtransferencia.setEnabled(true);
        jCotra.setEnabled(true);
        jCreingreso.setEnabled(true);
        jCreingreso_traslado.setEnabled(true);
        jCtraslado.setEnabled(true);
        jTcual.setEnabled(true);
        }
    }//GEN-LAST:event_jCmodificacionActionPerformed

    private void jCreingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreingresoActionPerformed
        // TODO add your handling code here:
        if(jCreingreso.isSelected()==true){
        jCcambio.setEnabled(false);
        jCmodificacion.setEnabled(false);
        jCotra.setEnabled(false);
        jCtransferencia.setEnabled(false);
        jCreingreso_traslado.setEnabled(false);
        jCtraslado.setEnabled(false);
        jTcual.setEnabled(false);
        }
        else{
        jCcambio.setEnabled(true);
        jCmodificacion.setEnabled(true);
        jCotra.setEnabled(true);
        jCtransferencia.setEnabled(true);
        jCreingreso_traslado.setEnabled(true);
        jCtraslado.setEnabled(true);
        jTcual.setEnabled(true);
        }
    }//GEN-LAST:event_jCreingresoActionPerformed

    private void jCtransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtransferenciaActionPerformed
        // TODO add your handling code here:
        if(jCtransferencia.isSelected()==true){
        jCcambio.setEnabled(false);
        jCmodificacion.setEnabled(false);
        jCotra.setEnabled(false);
        jCreingreso.setEnabled(false);
        jCreingreso_traslado.setEnabled(false);
        jCtraslado.setEnabled(false);
        jTcual.setEnabled(false);
        }
        else{
        jCcambio.setEnabled(true);
        jCmodificacion.setEnabled(true);
        jCotra.setEnabled(true);
        jCreingreso.setEnabled(true);
        jCreingreso_traslado.setEnabled(true);
        jCtraslado.setEnabled(true);
        jTcual.setEnabled(true);
        }
        System.out.println(jCtransferencia.isSelected());
    }//GEN-LAST:event_jCtransferenciaActionPerformed

    private void jCreingreso_trasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreingreso_trasladoActionPerformed
        // TODO add your handling code here:
        if(jCreingreso_traslado.isSelected()==true){
        jCcambio.setEnabled(false);
        jCmodificacion.setEnabled(false);
        jCotra.setEnabled(false);
        jCreingreso.setEnabled(false);
        jCtransferencia.setEnabled(false);
        jCtraslado.setEnabled(false);
        jTcual.setEnabled(false);
        }
        else{
        jCcambio.setEnabled(true);
        jCmodificacion.setEnabled(true);
        jCotra.setEnabled(true);
        jCreingreso.setEnabled(true);
        jCtransferencia.setEnabled(true);
        jCtraslado.setEnabled(true);
        jTcual.setEnabled(true);
        }
    }//GEN-LAST:event_jCreingreso_trasladoActionPerformed

    private void jCcambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcambioActionPerformed
        // TODO add your handling code here:
        if(jCcambio.isSelected()==true){
        jCtransferencia.setEnabled(false);
        jCmodificacion.setEnabled(false);
        jCotra.setEnabled(false);
        jCreingreso.setEnabled(false);
        jCreingreso_traslado.setEnabled(false);
        jCtraslado.setEnabled(false);
        jTcual.setEnabled(false);
        }
        else{
        jCtransferencia.setEnabled(true);
        jCmodificacion.setEnabled(true);
        jCotra.setEnabled(true);
        jCreingreso.setEnabled(true);
        jCreingreso_traslado.setEnabled(true);
        jCtraslado.setEnabled(true);
        jTcual.setEnabled(true);
        }
    }//GEN-LAST:event_jCcambioActionPerformed

    private void jCtrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtrasladoActionPerformed
        // TODO add your handling code here:
        if(jCtraslado.isSelected()==true){
        jCcambio.setEnabled(false);
        jCmodificacion.setEnabled(false);
        jCotra.setEnabled(false);
        jCreingreso.setEnabled(false);
        jCreingreso_traslado.setEnabled(false);
        jCtransferencia.setEnabled(false);
        jTcual.setEnabled(false);
        }
        else{
        jCcambio.setEnabled(true);
        jCmodificacion.setEnabled(true);
        jCotra.setEnabled(true);
        jCreingreso.setEnabled(true);
        jCreingreso_traslado.setEnabled(true);
        jCtransferencia.setEnabled(true);
        jTcual.setEnabled(true);
        }
    }//GEN-LAST:event_jCtrasladoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(solicitud_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(solicitud_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(solicitud_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(solicitud_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); //hace parte de lo del marco de la interfaz
                    
                } catch (Exception ex) {
                    System.out.println("Error de recuadro interfaz");
                } 
                try{
                    new solicitud_interfaz().setVisible(true);
                }
                catch(Exception ex){
                    System.out.println("putto error de mierddaaaaaa");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCcambio;
    private javax.swing.JCheckBox jCmodificacion;
    private javax.swing.JCheckBox jCotra;
    private javax.swing.JCheckBox jCreingreso;
    private javax.swing.JCheckBox jCreingreso_traslado;
    private javax.swing.JCheckBox jCtransferencia;
    private javax.swing.JCheckBox jCtraslado;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLcual;
    private javax.swing.JLabel jLlogo_univalle;
    private javax.swing.JLabel jLtexto_superior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTcual;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
